### ISSUE TITLE
Visualization error on language selector (languages appear and disappear)

### ISSUE THREAD

**Issue by evilaliv3** [wp-premium/sitepress-multilingual-cms#1]
On globaleaks.org we are currently experiencing the following error:

We have a website using wpml and internationalized in 8 languages: ar, zh-hans, de, es, fr, hi, pt-br

- When the user is on the home page in English the menu shows correctly showing all the language/flags (url to reproduce: https://www.globaleaks.org/)
- When the user is on a the home page in a language != English the menu is showing all the languages/flags except the Portuguese-Brazilian (url to reproduce: https://www.globaleaks.org/pt-br/)

**Comment by remcotolsma** [comment]
> WPML Multilingual CMS, Git-ified. Synced manual! This repository is just a mirror of the MemberPress plugin. **Please do not send pull requests and issues.**

https://github.com/wp-premium/sitepress-multilingual-cms

**Comment by evilaliv3** [comment]
I see thanks @remcotolsma; we should users report software flaws?
